---
- name: PHP | Add depedencies to add PHP repo
  apt:
    name:
      - lsb-release
      - apt-transport-https
      - ca-certificates
    state: present
- name: PHP | Get PHP repo
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
- name: PHP | Install PHP repo
  copy:
    dest: /etc/apt/sources.list.d/php{{ php_version }}.list
    content: deb https://packages.sury.org/php/ stretch main
- name: PHP | Install
  apt:
    update_cache: yes
    name:
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-json"
    state: present
- name: PHP | Composer
  shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
- name: PHP | Disable Errors
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "display_errors ="
    line: "display_errors = 0"
- name: PHP | Ensure CSRF is enabled on PHPSESSID
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "session.cookie_samesite ="
    line: 'session.cookie_samesite = Lax'
  notify: php restart
